"""As migrações chegam ao mesmo schema que os modelos descrevem.

O resto da suíte cria as tabelas a partir dos modelos (`create_all`), então um modelo alterado
sem migração passa em todos os outros testes e só quebra no deploy. Este teste sobe as
migrações num banco vazio e roda o `alembic check`.

Só roda contra Postgres (`TEST_DATABASE_URL`): as migrações foram geradas para ele e não
rodam em sqlite. No dia a dia, quem faz essa conferência é o `./dev.sh`.
"""

import os
import sys
from pathlib import Path

import pytest
from sqlalchemy import create_engine, text

URL = os.getenv("TEST_DATABASE_URL")
BACKEND = Path(__file__).resolve().parent.parent

pytestmark = pytest.mark.skipif(not URL, reason="as migrações só rodam em Postgres")


def _empty_database():
    """Nem tabela dos modelos nem marca de versão do Alembic — os outros testes deixam as duas."""
    import app.models  # noqa: F401 — sem isto o metadata está vazio e o drop_all não apaga nada
    from app.database import Base

    engine = create_engine(URL)
    Base.metadata.drop_all(bind=engine)
    with engine.begin() as conn:
        conn.execute(text("DROP TABLE IF EXISTS alembic_version"))
    engine.dispose()


def test_migracoes_e_modelos_descrevem_o_mesmo_schema(monkeypatch):
    from alembic.config import Config

    from alembic import command

    # o env.py lê a URL de app.database, que a captura no import: recarrega apontando para cá
    monkeypatch.setenv("DATABASE_URL", URL)
    for mod in [m for m in sys.modules if m == "app" or m.startswith("app.")]:
        del sys.modules[mod]

    config = Config(str(BACKEND / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND / "alembic"))

    _empty_database()
    try:
        command.upgrade(config, "head")
        # levanta AutogenerateDiffsDetected quando modelo e migração divergem
        command.check(config)
    finally:
        _empty_database()
