"""id de importacao em lancamentos

Revision ID: 1505b7699a98
Revises: 32ec0540244b
Create Date: 2026-09-25 15:25:05.565941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1505b7699a98'
down_revision: Union[str, Sequence[str], None] = '32ec0540244b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lancamentos', sa.Column('id_importacao', sa.String(length=120), nullable=True))
    op.create_unique_constraint('uq_lancamento_importacao', 'lancamentos', ['usuario_id', 'id_importacao'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lancamento_importacao', 'lancamentos', type_='unique')
    op.drop_column('lancamentos', 'id_importacao')
    # ### end Alembic commands ###
